### ISSUE TITLE
display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/432.

### ISSUE THREAD

**Issue by mmflys** [testerSunshine/12306#92]
后台运行报这个信息,不知道是不是错

**Comment by Youngggg** [comment]
unable to open X server `' @ error/display.c/DisplayImageCommand/432.   我也是 docker中出现这个  求解答

**Comment by Aiiiiii** [comment]
hi，想问下这个问题最终如何解决的？

**Comment by mmflys** [comment]
没有解决

**Comment by a-runner** [comment]
I have the same problem

**Comment by ZurMaD** [comment]
This problem (Unable to open X Server) usually happens when executing code that uses GUI on only terminal computers. Also, in subsystems like WSL, WSL2. Or maybe with no controllers that handle the GUI display on the operative system. There's no easy solution, could be to re-write the code of the whole program to detect if there are screens to display the results and avoid their use if possible.
